/**
 * Comprehensive artist seed list for large-scale data collection
 * Organized by genre/era with focus on interconnected artists
 * Target: 1000+ artists
 */

// Classic Rock (1960s-1970s)
export const CLASSIC_ROCK = [
  "The Beatles",
  "The Rolling Stones",
  "Led Zeppelin",
  "Pink Floyd",
  "The Who",
  "Queen",
  "Deep Purple",
  "Black Sabbath",
  "Fleetwood Mac",
  "Eagles",
  "Aerosmith",
  "Kiss",
  "AC/DC",
  "Van Halen",
  "Lynyrd Skynyrd",
  "ZZ Top",
  "Boston",
  "Kansas",
  "Styx",
  "Journey",
  "Foreigner",
  "Heart",
  "Cheap Trick",
  "REO Speedwagon",
  "Def Leppard",
];

// Beatles Members & Solo
export const BEATLES_EXTENDED = [
  "John Lennon",
  "Paul McCartney",
  "George Harrison",
  "Ringo Starr",
  "Wings",
  "Plastic Ono Band",
  "Traveling Wilburys",
];

// 1960s-70s Singer-Songwriters
export const SINGER_SONGWRITERS = [
  "Bob Dylan",
  "Neil Young",
  "Joni Mitchell",
  "Leonard Cohen",
  "Cat Stevens",
  "James Taylor",
  "Carole King",
  "Simon & Garfunkel",
  "Paul Simon",
  "Art Garfunkel",
  "Crosby, Stills, Nash & Young",
  "David Crosby",
  "Stephen Stills",
  "Graham Nash",
  "Van Morrison",
  "Tom Petty",
  "Tom Petty and the Heartbreakers",
  "Bruce Springsteen",
  "Billy Joel",
  "Elton John",
];

// Psychedelic & Progressive Rock
export const PROG_PSYCH = [
  "Jimi Hendrix",
  "The Doors",
  "Cream",
  "Eric Clapton",
  "The Jimi Hendrix Experience",
  "Jefferson Airplane",
  "Grateful Dead",
  "The Velvet Underground",
  "Yes",
  "Genesis",
  "King Crimson",
  "Emerson, Lake & Palmer",
  "Jethro Tull",
  "Rush",
  "Supertramp",
  "Electric Light Orchestra",
  "10cc",
  "Alan Parsons Project",
  "Mike Oldfield",
  "Tangerine Dream",
];

// David Bowie Extended Universe
export const BOWIE_EXTENDED = [
  "David Bowie",
  "Iggy Pop",
  "The Stooges",
  "Lou Reed",
  "Brian Eno",
  "Roxy Music",
  "T. Rex",
  "Marc Bolan",
  "Mott the Hoople",
  "Tin Machine",
];

// Punk Rock (1970s-1980s)
export const PUNK = [
  "Ramones",
  "Sex Pistols",
  "The Clash",
  "The Damned",
  "Buzzcocks",
  "The Jam",
  "The Stranglers",
  "Dead Kennedys",
  "Black Flag",
  "Bad Brains",
  "Minor Threat",
  "Misfits",
  "Circle Jerks",
  "Descendents",
  "Social Distortion",
  "X",
  "The Germs",
  "Fugazi",
  "Bad Religion",
  "NOFX",
];

// Post-Punk & New Wave
export const POST_PUNK_NEW_WAVE = [
  "Joy Division",
  "New Order",
  "The Cure",
  "Siouxsie and the Banshees",
  "Echo & the Bunnymen",
  "Bauhaus",
  "The Sisters of Mercy",
  "The Mission",
  "Fields of the Nephilim",
  "Cocteau Twins",
  "Dead Can Dance",
  "Talking Heads",
  "Blondie",
  "Devo",
  "The B-52's",
  "XTC",
  "Wire",
  "Magazine",
  "Gang of Four",
  "Public Image Ltd",
  "Killing Joke",
  "The Fall",
  "The Smiths",
  "Morrissey",
  "Johnny Marr",
];

// Synth-Pop & Electronic 80s
export const SYNTH_POP = [
  "Depeche Mode",
  "New Order",
  "Pet Shop Boys",
  "Erasure",
  "Soft Cell",
  "Human League",
  "Orchestral Manoeuvres in the Dark",
  "Gary Numan",
  "Ultravox",
  "Duran Duran",
  "Spandau Ballet",
  "A-ha",
  "Tears for Fears",
  "Simple Minds",
  "INXS",
  "The Eurythmics",
  "Alphaville",
  "Yazoo",
  "Yaz",
  "Thompson Twins",
];

// Alternative Rock (1980s-1990s)
export const ALTERNATIVE_ROCK = [
  "R.E.M.",
  "U2",
  "The Smiths",
  "Pixies",
  "Sonic Youth",
  "Dinosaur Jr.",
  "Hüsker Dü",
  "The Replacements",
  "The Meat Puppets",
  "Violent Femmes",
  "Throwing Muses",
  "The Breeders",
  "Belly",
  "Lemonheads",
  "Buffalo Tom",
  "Pavement",
  "Guided by Voices",
  "Built to Spill",
  "Modest Mouse",
  "Sebadoh",
];

// Grunge & 90s Rock
export const GRUNGE_90S = [
  "Nirvana",
  "Pearl Jam",
  "Soundgarden",
  "Alice in Chains",
  "Stone Temple Pilots",
  "Mudhoney",
  "Screaming Trees",
  "Mother Love Bone",
  "Temple of the Dog",
  "Mad Season",
  "Foo Fighters",
  "Dave Grohl",
  "Chris Cornell",
  "Audioslave",
  "Eddie Vedder",
  "Kurt Cobain",
  "Hole",
  "L7",
  "Babes in Toyland",
  "Veruca Salt",
];

// Britpop & UK Rock 90s
export const BRITPOP = [
  "Oasis",
  "Blur",
  "Pulp",
  "Suede",
  "Elastica",
  "The Verve",
  "Manic Street Preachers",
  "Stereophonics",
  "Supergrass",
  "Placebo",
  "Travis",
  "Coldplay",
  "Radiohead",
  "Thom Yorke",
  "Atoms for Peace",
  "The Smile",
  "Jonny Greenwood",
  "Muse",
  "Keane",
  "Snow Patrol",
];

// Indie Rock 2000s-2010s
export const INDIE_2000S = [
  "The Strokes",
  "The White Stripes",
  "Jack White",
  "The Raconteurs",
  "The Dead Weather",
  "Interpol",
  "The National",
  "Arcade Fire",
  "LCD Soundsystem",
  "Yeah Yeah Yeahs",
  "TV on the Radio",
  "Vampire Weekend",
  "MGMT",
  "Grizzly Bear",
  "Fleet Foxes",
  "Bon Iver",
  "The War on Drugs",
  "Tame Impala",
  "Arctic Monkeys",
  "Franz Ferdinand",
  "Kaiser Chiefs",
  "Bloc Party",
  "The Libertines",
  "The Kooks",
  "Razorlight",
];

// Metal
export const METAL = [
  "Black Sabbath",
  "Ozzy Osbourne",
  "Iron Maiden",
  "Judas Priest",
  "Metallica",
  "Megadeth",
  "Slayer",
  "Anthrax",
  "Pantera",
  "Sepultura",
  "Motörhead",
  "Dio",
  "Rainbow",
  "Scorpions",
  "Accept",
  "Helloween",
  "Blind Guardian",
  "Nightwish",
  "Within Temptation",
  "Opeth",
  "Mastodon",
  "Tool",
  "A Perfect Circle",
  "System of a Down",
  "Slipknot",
  "Korn",
  "Deftones",
  "Nine Inch Nails",
  "Marilyn Manson",
  "Rammstein",
];

// Electronic - Pioneers
export const ELECTRONIC_PIONEERS = [
  "Kraftwerk",
  "Tangerine Dream",
  "Jean-Michel Jarre",
  "Vangelis",
  "Giorgio Moroder",
  "Klaus Schulze",
  "Brian Eno",
  "Cabaret Voltaire",
  "Throbbing Gristle",
  "Suicide",
  "Yellow Magic Orchestra",
  "Ryuichi Sakamoto",
];

// IDM & Experimental Electronic
export const IDM_EXPERIMENTAL = [
  "Aphex Twin",
  "Autechre",
  "Boards of Canada",
  "Squarepusher",
  "Plaid",
  "μ-Ziq",
  "Venetian Snares",
  "Amon Tobin",
  "Prefuse 73",
  "Flying Lotus",
  "Four Tet",
  "Caribou",
  "Burial",
  "The Knife",
  "Fever Ray",
  "Björk",
  "Radiohead",
];

// House & Techno
export const HOUSE_TECHNO = [
  "Daft Punk",
  "The Chemical Brothers",
  "The Prodigy",
  "Fatboy Slim",
  "Underworld",
  "Orbital",
  "The Orb",
  "Leftfield",
  "Massive Attack",
  "Portishead",
  "Tricky",
  "Morcheeba",
  "Air",
  "Röyksopp",
  "Justice",
  "Deadmau5",
  "Skrillex",
  "Disclosure",
  "Bonobo",
  "Jon Hopkins",
];

// Trip-Hop & Downtempo
export const TRIP_HOP = [
  "Massive Attack",
  "Portishead",
  "Tricky",
  "Morcheeba",
  "Sneaker Pimps",
  "Hooverphonic",
  "Lamb",
  "UNKLE",
  "DJ Shadow",
  "Bonobo",
  "Thievery Corporation",
  "Zero 7",
  "Nightmares on Wax",
  "Kruder & Dorfmeister",
  "Tosca",
];

// Hip-Hop Classics
export const HIP_HOP = [
  "Run-D.M.C.",
  "Public Enemy",
  "N.W.A",
  "Ice Cube",
  "Dr. Dre",
  "Snoop Dogg",
  "Tupac Shakur",
  "The Notorious B.I.G.",
  "Wu-Tang Clan",
  "A Tribe Called Quest",
  "De La Soul",
  "The Roots",
  "OutKast",
  "Nas",
  "Jay-Z",
  "Eminem",
  "Kanye West",
  "Kendrick Lamar",
  "J. Cole",
  "Tyler, the Creator",
];

// R&B & Soul
export const RNB_SOUL = [
  "Marvin Gaye",
  "Stevie Wonder",
  "Aretha Franklin",
  "Al Green",
  "Curtis Mayfield",
  "Isaac Hayes",
  "Barry White",
  "Earth, Wind & Fire",
  "Chic",
  "Prince",
  "Michael Jackson",
  "Janet Jackson",
  "Whitney Houston",
  "Sade",
  "Erykah Badu",
  "D'Angelo",
  "Lauryn Hill",
  "Frank Ocean",
  "The Weeknd",
  "SZA",
];

// Jazz & Jazz-Rock
export const JAZZ = [
  "Miles Davis",
  "John Coltrane",
  "Herbie Hancock",
  "Chick Corea",
  "Weather Report",
  "Return to Forever",
  "Pat Metheny",
  "Mahavishnu Orchestra",
  "Frank Zappa",
  "Steely Dan",
  "Donald Fagen",
  "Sting",
  "The Police",
  "Snarky Puppy",
  "Kamasi Washington",
  "Robert Glasper",
  "Thundercat",
  "Flying Lotus",
  "Hiatus Kaiyote",
  "Jacob Collier",
];

// World Music & Global
export const WORLD = [
  "Fela Kuti",
  "King Sunny Adé",
  "Youssou N'Dour",
  "Salif Keita",
  "Ali Farka Touré",
  "Tinariwen",
  "Amadou & Mariam",
  "Oumou Sangaré",
  "Angélique Kidjo",
  "Buena Vista Social Club",
  "Compay Segundo",
  "Ibrahim Ferrer",
  "Manu Chao",
  "Gotan Project",
  "Rodrigo y Gabriela",
];

// Japanese Artists
export const JAPAN = [
  "Yellow Magic Orchestra",
  "Ryuichi Sakamoto",
  "Cornelius",
  "Pizzicato Five",
  "Shibuya-kei",
  "Fishmans",
  "Number Girl",
  "Asian Kung-Fu Generation",
  "Mono",
  "Boris",
  "Melt-Banana",
  "Boredoms",
  "toe",
  "Tricot",
  "One Ok Rock",
];

// All artists combined
export const ALL_SEED_ARTISTS = [
  ...CLASSIC_ROCK,
  ...BEATLES_EXTENDED,
  ...SINGER_SONGWRITERS,
  ...PROG_PSYCH,
  ...BOWIE_EXTENDED,
  ...PUNK,
  ...POST_PUNK_NEW_WAVE,
  ...SYNTH_POP,
  ...ALTERNATIVE_ROCK,
  ...GRUNGE_90S,
  ...BRITPOP,
  ...INDIE_2000S,
  ...METAL,
  ...ELECTRONIC_PIONEERS,
  ...IDM_EXPERIMENTAL,
  ...HOUSE_TECHNO,
  ...TRIP_HOP,
  ...HIP_HOP,
  ...RNB_SOUL,
  ...JAZZ,
  ...WORLD,
  ...JAPAN,
];

// Remove duplicates
export const UNIQUE_SEED_ARTISTS = [...new Set(ALL_SEED_ARTISTS)];

console.log(`Total unique seed artists: ${UNIQUE_SEED_ARTISTS.length}`);
